spring.application.name=QuizApp

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update

logging.level.com.quiz.QuizApp.controllers.QuizController=DEBUG
app.frontend.url=${APP_FRONTEND_URL}

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_FROM_NUMBER}

server.port=${PORT:8080}

logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.com.zaxxer.hikari=DEBUG